### ISSUE TITLE
Feature request: allow globing workspace path and not anly their names

### ISSUE THREAD

**Issue by Offirmo** [boltpkg/bolt#102]
In a big mono-repo subdivided in sub-directories, I'd like to be able to mass-build only some packages/workspaces under a sub-directory.

Example here: https://github.com/Offirmo/hello-world-bolt/tree/master/pro I'd like to be able to `bolt w run build` only the workspaces under `/pro` and not *all* my mono-repo workspaces.

Will `--only-fs` (currently not implemented) work on the path of the workspace or only on the workspace name?

**Comment by lukebatchelor** [comment]
Yup. Only fs will do that. It should be implemented with run already. Were you using w (workspace) or ws (workspaces)? Ws /should/ work with only fs

**Comment by ajaymathur** [comment]
filters on workspaces are implemented, updated the readme here: https://github.com/boltpkg/bolt/pull/103

**Comment by ajaymathur** [comment]
can use `bolt workspaces exec --only-fs 'pro/**' -- [cmd]`

reference: https://bitbucket.org/atlassian/atlaskit-mk-2/src/aa4bd23ebf95fed7dbbd97adf30717c2343139d9/package.json?at=master&fileviewer=file-view-default#package.json-14
