### ISSUE TITLE
bolt ws clear

### ISSUE THREAD

**Issue by ajaymathur** [boltpkg/bolt#106]
| Title         | Description
| ---------------- | -------
|Version| Latest 
| Type          | Feature Request 
| node             |  8.9.4
| Operating System | High Sierra
|Detailed description| this will clear all the workspaces without package json, so that we don't need to delete workspaces manually while switching branches

**Comment by thejameskyle** [comment]
I think we should just start ignoring directories without a package.json, basically in the opposite direction of this: https://github.com/boltpkg/bolt/commit/27c74420f2cf6478dc90c16b90ee331c2461c110
