### ISSUE TITLE
Is there a changelog somewhere?

### ISSUE THREAD

**Issue by Offirmo** [boltpkg/bolt#130]
| Title               | Description
| --------------------|------------
| Version             | 0.19.2
| Type                |  Request
| Short Description   | Have a CHANGELOG

Would be nice. Thanks for the good work.

**Comment by thejameskyle** [comment]
I don't think we're going to maintain a changelog until we hit 1.0 which should be in a few months

**Comment by Offirmo** [comment]
Fine for me. Was just curious when upgrading to 0.19.

You can close this issue if you want.

**Comment by ajaymathur** [comment]
Closing this: will create changelog from version 1.
