### ISSUE TITLE
Isn't a issue just to say thank you 

### ISSUE THREAD

**Issue by romulocintra** [boltpkg/bolt#145]
Hi guys from bolt , 

From last 2 weeks i've been experimenting lots of tooling related with monorepo management and all of them have some Pros/Cons , after doing some test drive with bolt/rush/lerna ... i started using lerna as my main monorepo manager and after 1 week using it i was missing the simplicity of bolt... there are lots of things going on... i know ... but after that i moved back to bolt and hope that you do not run away and get more people using it and contributing with you on this nice nice tool and journey. 

I was suprised that also this guys moved to bolt... 

https://bitbucket.org/atlassian/atlaskit-mk-2/src/8dc8b67506e8f91089dd04e7fee4bf576635c553/package.json?at=master&fileviewer=file-view-default

Thanks a lot ...

**Comment by lukebatchelor** [comment]
Thats actually the first user of bolt, Atlaskit by Atlassian, the mk-2 there is because we moved from Lerna as well ;p (it'll be renamed back to the old name soon since the migration between repos is done).

Thanks for thank you, always appreciated. :)

**Comment by thejameskyle** [comment]
lol, they were super smart to move to Bolt
