### ISSUE TITLE
Override npm_config_user_agent env var so bolt can be detected

### ISSUE THREAD

**Issue by bengummer** [boltpkg/bolt#148]
I'd like to use the `npm_config_user_agent` (already set by `npm` and `yarn`) to detect whether `bolt` is being run in my project's `preinstall` script.

Currently npm / yarn set the following values for the `npm_config_user_agent` env var

* yarn (and bolt because it is unchanged): `yarn/1.3.2 npm/? node/v8.9.4 darwin x64`
* npm: `npm/5.6.0 node/v8.9.4 darwin x64`

Ideally bolt will prepend `bolt/<bolt version> ` to the existing env var value set by yarn.

**Comment by bengummer** [comment]
I can't assign this to myself but i'll raise a PR for it :)

**Comment by lukebatchelor** [comment]
Heya @bengummer , did you ever end up getting this working? The code is in there and the tests pass, but I just tested it, and it seems to not be showing up

```
"scripts": {
  "preinstall": "echo $npm_config_user_agent"
}
```

```
$ bolt install
⚡️   bolt v0.22.2 (node v8.11.3)
🔎   [1/4] Validating project...
📦   [2/4] Installing project dependencies...
yarn config get user-agent yarn/1.9.4 npm/? node/v8.11.3 darwin x64
yarn install v1.9.4
$ echo $npm_config_user_agent
yarn/1.9.4 npm/? node/v8.11.3 darwin x64
```

I think yarn might actually be re-overriding it when we call `yarn install`?

CC: @randing89

**Comment by bengummer** [comment]
Hey @lukebatchelor yeah you might be right, I'm not using this user agent anymore in our project that uses Bolt so haven't really noticed if it behaves as expected or not. Maybe a different env var (such as the `BOLT_VERSION` mentioned in recent commits would be better to avoid yarn overwriting it.

**Comment by lukebatchelor** [comment]
Sweet. Yea. Thought so. Cheers
