### ISSUE TITLE
Add bolt Clear/Clean

### ISSUE THREAD

**Issue by romulocintra** [boltpkg/bolt#153]
**Feature Request** 

`bolt clear`

Add bolt clean or clear   command to clean all node_modules from root and nested packages/workpsaces

**Comment by thejameskyle** [comment]
There are better solutions to getting to a fresh `node_modules` state than nuking everything

**Comment by romulocintra** [comment]
Just asking for similar command that you can find in  all similar projects... 
is not a difficult feature but handy in several cases when you run in  local , CI etc... or even when your testing the tool ... anyway thanks for the answer

**Comment by thejameskyle** [comment]
Also, there's a pretty decent command for this already:

```
rm -rf node_modules && bolt ws exec -- rm -rf node_modules
```
