### ISSUE TITLE
Too many "What kind of change is this for <package>" questions

### ISSUE THREAD

**Issue by pcurren** [boltpkg/bolt#155]
When I run bolt changeset the first question I'm asked is what packages I would like to include.
I select one package, and then I seem to be asked:
"What kind of change is this for <some package>"
for every other package in my build.

The answer (for the patch type changes I am making anyway) is always None, None, None, None, None, etc.

Can this be optimised at all?

**Comment by pcurren** [comment]
Maybe it's only asking me for every dependent package actually. That's still quite a few Nones though.

**Comment by lukebatchelor** [comment]
Bolt changeset is a script in our repo, not a bolt command.

But yes, indeed, I'll be working on that this week actually. We'll be relaxing the strictness of "correct-ness" by automatically assuming any change that *can* be none, will be none, and users can explicitly create a separate changeset if they need to bump a dependent together.

**Comment by lukebatchelor** [comment]
And yup, it's every dependent package, which because of the structure of our dep tree, links way too many packages (by time you iterate three levels deep, almost every single package is a dependent of every other due to shared dependencies like theme and docs)

**Comment by ajaymathur** [comment]
closing this as it is not related to bolt .
