### ISSUE TITLE
Messages possibly arriving out of order?

### ISSUE THREAD

**Issue by lukebatchelor** [boltpkg/bolt#167]
Not 100% sure, but I've seen a few little things that haven't made sense that make me thing that maybe some messages aren't arriving in order. And not just with tasks that are running in parallel.

Installing for example:

```
⚡️   bolt v0.20.5 (node v8.9.0)
🔎   [1/3] Validating project...
📦   [2/3] Installing project dependencies...
🔗   [3/3] Linking workspace dependencies...
$ /Users/lbatchelor/src/bolt-pkg/bolt/node_modules/.bin/yarn config get user-agent yarn/1.6.0 npm/? node/v8.9.0 darwin x64
yarn install v1.6.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 2.40s.
💥  success Installed and linked workspaces.
🏁   Done in 11.42s.
```

It says '[3/3] Linking workspace dependencies...' before we see any output from the `yarn install` step itself.

I might have a little dig later, it might be something in spawn not flushing a buffer when a task finishes maybe?

**Comment by jamiebuilds** [comment]
You fucked it #169
