### ISSUE TITLE
Bolt add does not upgrade existing packages

### ISSUE THREAD

**Issue by Blasz** [boltpkg/bolt#170]
| Title               | Description
| --------------------|------------
| Version             | 0.19.3
| Type                | Issue
| node                | 8.4.0
| Operating System    | macOS 10.13.4
| Short Description   | Bolt add does not upgrade a dependency that already exists in the repo

E.g. if `extract-react-types` exists in the root package.json with version `"^0.10.0"` and I run `bolt add extract-react-types@^0.11.0` it will not upgrade the package at that version.

Running the same command with yarn upgrades the package correctly: `yarn add extract-react-types@^0.11.0`.

Is this something `bolt add` should handle or is this solely supposed to be handled by `bolt upgrade`?

**Comment by lukebatchelor** [comment]
Good question. This likely would have been before I knew about that side effect of yarn, so entirely possible it was missed.

 Let me take a look and see what the impact of adding it would be.

**Comment by Blasz** [comment]
👌 I'm happy to contribute if this gets the green light.
