### ISSUE TITLE
Bolt upgrade malforms package.json when dependency declared multiple times in package.json

### ISSUE THREAD

**Issue by Blasz** [boltpkg/bolt#171]
| Title               | Description
| --------------------|------------
| Version             | 0.19.3
| Type                | Issue
| node                | 8.4.0

When a package is declared in multiple different dependency types in a workspace's package.json, e.g. dependencies and devDependencies, `bolt upgrade` will add a new entry to package.json with the dependency entry names concatenated:

E.g. 

```
"dependencies,devDependencies": {
  "bunyan": "^1.8.12"
}
```

I'm happy to take a look and create a PR for this.

**Comment by lukebatchelor** [comment]
Hmmm.. that definitely should be fixed, but possibly wasn't in until 0.20? Could you try upgrading?

**Comment by Blasz** [comment]
Upgraded to 0.20.6 and it's fixed, cheers @lukebatchelor.

**Comment by lukebatchelor** [comment]
I know we didn't want a changelog till 1.0.0 but I might add a quick manual one if I get time later. Useful for this situation
