### ISSUE TITLE
Recommended package.json for bolt build (with babel)

### ISSUE THREAD

**Issue by lifeiscontent** [boltpkg/bolt#176]
Hi guys, I'd love to see the example updated, or my question answered, using bolt+babel, do you have an example of how the package.json should be structured in order to provide the best packaging experience using es6 so a package can be consumed in different use cases, e.g. browser/node.

**Comment by jamiebuilds** [comment]
`package.json#scripts` work exactly the same as in Yarn.

**Comment by lifeiscontent** [comment]
@jamiebuilds do you know of a tutorial I could follow for building packages with babel?

**Comment by ajaymathur** [comment]
Hi @lifeiscontent , Please take a look at https://github.com/bookercodes/articles/blob/master/how-to-build-and-publish-es6-npm-modules-today-with-babel.md , it might help 🙂
