### ISSUE TITLE
.yarnrc

### ISSUE THREAD

**Issue by lifeiscontent** [boltpkg/bolt#204]
| Title               | Description
| --------------------|------------
| Version             | N/A
| Type                | question
| node                | N/A
| Operating System    | N/A
| Short Description   | should I use `.yarnrc` with bolt?
| Detailed description| using bolt, is it recommended to pair it with yarn workspaces using `.yarnrc`

**Comment by ajaymathur** [comment]
@lifeiscontent Bolt uses yarn under the hood thus yarn should respect you `.yarnrc` file. Though, what would pair it with yarn workspaces using `.yarnrc` mean in this context?

**Comment by lukebatchelor** [comment]
@lifeiscontent All the yarnrc settings should work, but no, you don't need to set `workspaces-experimental `

👍
