### ISSUE TITLE
RegExp in workspaces setup

### ISSUE THREAD

**Issue by Dechowmedia** [boltpkg/bolt#211]
| Title               | Description
| --------------------|------------
| Version             | 0.22.5
| Type                | Issue (/ Feature Request perhaps)
| node                | 10.13.0
| Operating System    | Windows
| Short Description   | I hoped the workspaces were RegExp based and not just globbing
| Detailed description| I wanted to ignore a certain folder from my setup such I could run a frontend and a API side-by-side in a project (within different workspaces) but it wouldn't ignore the folder.

I was utilising Next.js for the front-end and micro for the API (but that should not have any effect on this)

I added a workspace config that should ignore a folder, but it was not accepted e.g.:
```
...
  "bolt": {
    "workspaces": [
      "api/**/*",
      "www/*",
      "!www/pages/*"
    ]
  },
...
```

**Comment by jamiebuilds** [comment]
Workspace configs should definitely not be regexes, globs are significantly better. But what you have is invalid either way. `www/*` would never match anything in `www/pages/*`, because it's matching `www/pages` itself.

This is likely what you meant: 

```json
...
  "bolt": {
    "workspaces": [
      "api/**/*",
      "www/*",
      "!www/pages"
    ]
  },
...
```
