### ISSUE TITLE
Feature request: Support yarn `--frozen-lockfile`

### ISSUE THREAD

**Issue by Offirmo** [boltpkg/bolt#237]
| Title               | Description
| --------------------|------------
| Version             | 0.23.5
| Type                | feature Request
| node                | 10
| Short Description   | Support yarn `--frozen-lockfile`
| Detailed description| 

In the same way that `--pure-lockfile` is supported, we should have a way to support `--frozen-lockfile`, especially useful for CI.

I can't do the PR because the best way to change it is to turn `pureLockfile: boolean` into a more powerful `lockfileMode: 'default' | 'pure' | 'frozen'` but that's above my flow level :-(

**Comment by lukebatchelor** [comment]
Hmm.. I'd think we'd just add it as a separate flag right? We pass it directly onto yarn anyway, so I don't think we'd deviate from their API?

I'd be happy to accept it if you like.

**Comment by Offirmo** [comment]
Actually it wasn't that hard: https://github.com/boltpkg/bolt/pull/238

**Comment by lukebatchelor** [comment]
Closed in #238

**Comment by lukebatchelor** [comment]
Released in 0.23.6
