### ISSUE TITLE
Missing `context` in `SlackCommandMiddlewareArgs` type

### ISSUE THREAD

**Issue by Hugo-Contreras** [boltpkg/bolt#268]
| Title               | Description
| --------------------|------------
| Version             | ^1.6.0
| Type                | Issue
| node                | 12.13.0
| Operating System    | macOS
| Short Description   | Missing `context` in `SlackCommandMiddlewareArgs` type
| Detailed description| When using Bolt with TypeScript and listening to a command I want to use the context param to get the token as specified in the documentation but it's missing from the type definition so I have to @ts-ignore

**Comment by lukebatchelor** [comment]
I think you might have the wrong repo. We don't have anything to do with slack middleware or context Params sorry.

**Comment by Hugo-Contreras** [comment]
Oops my bad, wrong repo
