### ISSUE TITLE
Is Bolt dead?

### ISSUE THREAD

**Issue by jmitchell38488** [boltpkg/bolt#289]
It appears as though there has been little to no action on this repository in a year & half.

Is this tool still being maintained or is it abandonware?

**Comment by lukebatchelor** [comment]
Bolt does what it does well and we've not needed to build anything else into it in some time. We work on it when we need some use case / fix for our companies or when we want to (in our own unpaid time).

If you have a (constructive) issue, you can raise it and if someone has the time or inclination they might help. If you have a fix and provide a pr then people might merge it.

Other than that, no, no one is spending time being busy in a repo to keep up a pretense of not being "dead" (when you admit yourself that you're completely aware that there's been multiple bug fixes merged from many people in the last year?).

**Comment by jmitchell38488** [comment]
@lukebatchelor thanks for the reply. Is this a sponsored (org) maintained tool, or OSS? As best as I could tell, one of the major users of Bolt was the Atlassian Mk2 component library, around the time the library was migrated from v1 to v2, from lerna.

**Comment by lukebatchelor** [comment]
It's OSS, yup.
