### ISSUE TITLE
bolt install --full ?

### ISSUE THREAD

**Issue by Haskaalo** [boltpkg/bolt#87]
I use bolt in a monorepo but instead of using it to publish packages to npm registry, I use it to deploy web applications to docker. Because bolt only create symlinks, if I run `bolt install` in a directory and for example I tar the directory. The tar archive will not contain all node_modules required to run the application.

My idea is introducing `bolt install --full`. It will install alllllll dependencies off a **project** and no symlinks.

**Comment by lukebatchelor** [comment]
If you're going to install all of them, doesn't that defeat the purpose of using bolt? 

A four line shell file would let you just run `yarn install` in every package if you wanted. 

Otherwise you could look at the predecessor to this,  `lerna` which would probably suite better (at the cost of speed)

**Comment by Haskaalo** [comment]
@lukebatchelor 
I understand

But let's say that this is my current project.
```
│   package.json
│
├───p1
│       package.json
│
├───p2
│       package.json
│
└───p3
        package.json
```

Let's say `p2` is a web server and require `p1`.
and p3 is another package but doesn't require `p1` or `p2` but some others packages in the repository.

How would I install required packages for `p2` because I want for example to tar p2 or docker push p2.

## Why?

Because for a small/medium project I don't see the need to create a private npm registry (server cost 😞 ) and a CI is enough to do the job I think.

**Comment by lukebatchelor** [comment]
I'm not sure what you're asking.

If you want to install the deps on p2 you could

* have a script that does `cd p2 && yarn install`
* have a prepublish script in p2 that runs `rm -rf node_modules && yarn install`
* you could use lerna with the `--scope` flag

There are tons of options, none of which have anything to do with a private npm registry

**Comment by Haskaalo** [comment]
Ah I see thank you!

**Comment by thejameskyle** [comment]
One liner if you want to install all the workspaces separately:

```
bolt workspaces exec -- yarn install
```
